zookeeper:
  address:
    - 127.0.0.1:2181
  timeout: 10000
  protocol: zookeeper
  namespace: cm-user-server
  file: cmcc-user-servers

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://43.240.248.111:3306/cmcc_manager?useUnicode=true&characterEncoding=utf8
    username: root
    password: Haier@123
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-idle: 2
    max-wait: 60000
    test-while-idle: true
    min-evictable-idle-time-millis: 1800000
    time-between-eviction-runs-millis: 600000
    test-on-borrow: true
    test-on-return: false
    validation-query: SELECT 1
  redis:
    hostName: 43.240.248.111
    port: 6379
    maxIdle: 8
    timeout: 0
    pool.maxActive: 8
    pool.maxWait: -1
    pool.minIdle: 0
    password: Haier@123
