zookeeper:
  address:
    - 172.17.30.11:2181
    - 172.17.30.12:2181
    - 172.17.30.13:2181
  timeout: 10000
  protocol: zookeeper
  namespace: cmcc-user-server

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-2zep7p58q7425w6ea.mysql.rds.aliyuncs.com:3306/cac_hm_platform?useUnicode=true&characterEncoding=utf8
    username: haierac_cac
    password: A%C7gPvdQTOjr3SB
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-idle: 2
    max-wait: 60000
    test-while-idle: true
    min-evictable-idle-time-millis: 1800000
    time-between-eviction-runs-millis: 600000
    test-on-borrow: true
    test-on-return: false
    validation-query: SELECT 1
  redis:
    hostName: r-2ze9685da31e8de4.redis.rds.aliyuncs.com
    port: 6379
    maxIdle: 8
    timeout: 10000
    pool.maxActive: 8
    pool.maxWait: -1
    pool.minIdle: 0
    password: ep9gJL3RmNqL3zQx
    database: 2